### ISSUE TITLE
do not assume that every patched repo has submodules

### ISSUE THREAD

**Issue by zachgersh** [pivotal-cf-experimental/knit#13]
Had an issue come up where the community asked for help using knit (I know):

http://stackoverflow.com/questions/43887870/update-bosh-releases-using-knit

The repo attached to the issue has no submodules BUT `knit` always assumes that on a checkout it should be attempting to init submodules.

Offending code here:

https://github.com/pivotal-cf-experimental/knit/blob/master/patcher/repo.go#L49

We need to check that a repo actually _has_ submodules before attempting to do this

**Comment by joshzarrabi** [comment]
We failed to reproduce this issue, perhaps the user was using an old version of git or knit.

See our stackoverflow answer here: https://stackoverflow.com/a/44686682/7169403
