### ISSUE TITLE
Feedback from CAPI team

### ISSUE THREAD

**Issue by ljfranklin** [pivotal-cf-experimental/knit#9]
Just got a chance to do some knitting and submit some pcf-patches for the first time. Neat little tool!

It worked out of the box, but there were a couple points that confused us a bit:
- The `knit -h` output is pretty bare, would be nicer to have the flag descriptions from the README.
- The `-version` flag is a bit confusing as there are several version numbers in play, e.g. ERT version, CAPI version. Also could this flag be made optional and default to the latest version of ERT?
- Seems like this tool creates a new branch matching the ERT version in `repository-to-patch`, e.g. 1.10.1. We'd rather it didn't create this branch in an OSS project like capi-release if possible.

We followed this [CAPI-specific doc](https://docs.google.com/document/d/12sCYkkq7XmT_9rMogwGBSfShDio-AyoJt2rkR0E8yfI/edit#) around the knitting steps, not sure if anything in there could be merged into the README.

👍

**Comment by zachgersh** [comment]
@ljfranklin - love the feedback and just saw this, so great.

1. Yeah, we can improve the info here.
2. Can we name this flag better? I think defaulting it may be fine.
3. Where would you like the branch to be created?

**Comment by ljfranklin** [comment]
1. Sweet
2. maybe `--ert-version`?
3. No branch in the source repo would be ideal as capi-release repo shouldn't know about ERT versions. If a branch is needed to make the git plumbing work then maybe prefix the branch with `ert-` or remove the branch when finished.

**Comment by davewalter** [comment]
Hi @ljfranklin,

We've pulled these requests out into separate stories in our icebox and will discuss with our PM for prioritisation. Feel free to follow along there if you are interested.

Thanks,
Dave
